### ISSUE TITLE
Add Map from TXM

### ISSUE THREAD

**Issue by ghost** [Harha/trackmania-server-docker#5]
Hey,

I use the trackmania 2020 server with PyPlanet using this docker compose yaml. I get the server running and the pyplanet overlay etc. works.

My problem is, that I can not add a map from TMX with command 
```
//tmx add <ID>
```
Instead I get the following error:

"Can't check or create folder: [Error 2] No such file or directory: '/home/server/tm_server/UserData/Maps/PyPlanet-MX"

Has anybody experienced that issue? Is this an issue because this solution is running in docker containers or is that a PyPlanet issue or my issue?

The command
```
//shuffle
```
for example works.

Greetings

**Comment by Harha** [comment]
Hey, thanks for submitting an issue!

I wasn't even aware that pyplanet supports importing maps from tmx via commands. It seems like it imports the maps into another folder called "PyPlanet-MX", which doesn't exist in the docker-compose YAML configuration file.

I would suggest creating a docker volume for these maps or organizing your current local host machine "maps" folder so that it represents the '/home/server/tm_server/UserData/Maps/' folder instead of './maps:/home/server/tm_server/UserData/Maps/Campaigns'.

So you can do this (and remember to reorganize the './maps' folder):
```yaml
volumes:
  - ./cfg_server.xml:/home/server/tm_server/UserData/Config/cfg_server.xml:Z
  - ./cfg_tracklist.xml:/home/server/tm_server/UserData/Maps/MatchSettings/cfg_tracklist.xml:Z
  - ./maps:/home/server/tm_server/UserData/Maps:Z <-- this was changed!
```

Or you can do this (create a new './maps_tmx' folder):
```yaml
volumes:
  - ./cfg_server.xml:/home/server/tm_server/UserData/Config/cfg_server.xml:Z
  - ./cfg_tracklist.xml:/home/server/tm_server/UserData/Maps/MatchSettings/cfg_tracklist.xml:Z
  - ./maps:/home/server/tm_server/UserData/Maps/Campaigns:Z
  - ./maps_tmx:/home/server/tm_server/UserData/Maps/PyPlanet-MX:Z
```

I will update the repository compose example with the first solution.

**Comment by Harha** [comment]
I added a commit that fixes this issue in the compose example setup. Please comment here if you get it working or if there's still some issue.

**Comment by ghost** [comment]
Hey, I pulled your changes but still receive the same error as before. But: I connected inside the server container and I can confirm the directory PyPlanet-MX exists with the path /home/server/tm_server/UserData/Maps/PyPlanet-MX

Did the solution work on your server?

**Comment by Harha** [comment]
@IR0B1NI Okhay, that's weird. I have a running server that I use for testing but I've just built a new PC and I don't have trackmania 2020 yet installed, so I cannot test it right now.

I'll get back to it later this evening and see if it works.

**Comment by ineentho** [comment]
I have the tmx commands working on my server. I have my server configured exactly as Harha suggested above:
```
      - ./maps:/home/server/tm_server/UserData/Maps:Z
```

Have you double checked that the permissions are correct? The server, by default, runs as UID 1000. This is what it should look like inside the container:
```
> docker-compose exec controller ls -lah /home/server/tm_server/UserData/Maps
total 40K
drwxr-xr-x 8 server server 4.0K Apr  9 16:32  .
drwxr-xr-x 3 root   root   4.0K Apr  9 16:35  ..
drwxr-xr-x 2 server server 4.0K Jan 28 02:57  Campaigns
drwxr-xr-x 2 server server 4.0K Jan 28 02:57  Challenges
drwxr-xr-x 2 server server 4.0K Apr  9 16:32  Downloaded
drwxr-xr-x 2 server server 4.0K Apr  9 16:32  MatchSettings
drwxr-xr-x 2 server server 4.0K Feb 21 17:40 'My Maps'
drwxr-xr-x 2 server server  12K Apr  9 16:32  PyPlanet-MX
```

If that's not the case, try chowning them on the host by doing something like this:
```
sudo chown -R 1000:1000 maps/
```

**Comment by ghost** [comment]
Executing this command on my pyplanet container generates no output.
Connecting inside the server container and execute

```
ls -lah Maps/
```

generates

```
total 32K
drwxr-xr-x 7 server server 4.0K Apr 10 10:58  .
drwxrwxrwx 1 server server 4.0K Apr 10 10:53  ..
drwxr-xr-x 2 server server 4.0K Apr 10 10:58  Campaigns
drwxr-xr-x 2 server server 4.0K Apr 10 10:53  Downloaded
drwxr-xr-x 2 server server 4.0K Apr 10 10:49  MatchSettings
drwxr-xr-x 2 server server 4.0K Apr 10 10:53 'My Maps'
drwxr-xr-x 2 server server 4.0K Apr 10 10:49  PyPlanet-MX
```

Still not working after chowning the maps/ directory.

**Comment by ineentho** [comment]
> Executing this command on my pyplanet container generates no output.

I believe you have to mount the maps volume to both containers, that may be the problem? To my knowledge pyplanet writes the file and the tmserver reads it.

**Comment by ghost** [comment]
Thank you very much! That worked! Simply added the maps volume to the controller. Please add that to the docker compose file.

**Comment by Harha** [comment]
Great, thanks both. I created a small fix commit, please note the lower-case 'z' flag in the mounted Maps volume. Lower-case 'z' basically means that this exact volume is shared between multiple containers.
