### ISSUE TITLE
Strange error

### ISSUE THREAD

**Issue by shaggywolfhound** [Harha/trackmania-server-docker#6]
Hopefully you can help.  I can't seem to get passed an error I get on the server:
...ERROR: Map lightmap is not up to date.

I've added /computeallshadows to your sh file but still the same error.  Any ideas?

**Comment by Harha** [comment]
No I haven't seen that error and I just tried the latest images and they run without any errors on my debian linux server.

Can you post more info about your setup? Did you use the docker-compose example included in the `./compose` folder as a starting point? What distro are you running on the host machine?

Are you sure the track you're trying to boot your server into isn't malformed?

**Comment by shaggywolfhound** [comment]
It's on my unraid server.  I've used your example docker-compose as is since I knew that it works be the first thing you can back with. The only thing I have changed, which I obviously had to do is add a map. That's one of the reasons I'm think that is where the issue is maybe. Have you got an example map you know that works, at least then I can take that out off the equation.

**Comment by Harha** [comment]
Here is a very simple (and bad) LoL map that should work just fine. I've run my own short map server with this image using docker-compose at least 6 months now and I haven't encountered a single map that wouldn't work. https://trackmania.exchange/tracks/view/3780

I don't know what is unraid, but I quickly googled and noticed that it might be some kind of networked RAID hard drive system? If that's the case, I'm not sure if such things work out-of-the-box with default docker filesystem/network drivers.

**Comment by shaggywolfhound** [comment]
It should work fine since I am running quite a few others with 0 problems (plex, swag etc), .  I'll give that map a go later on today, currently running a parity check on my server which tends to eat the processors.  I'll let you know how I get on.  If that then doesn't work I may try a vm to see if that is any different.  Cheers for your help btw.

**Comment by shaggywolfhound** [comment]
That map now loads.  Which is rather interesting, sorry but can you give me another example of a map I can use you know works and also is there a way I can import the standard maps e.g. TMStadium@nadeo.Title.Pack.gbx  Where would you normally download maps from?

Chances are there is something I'm doing ever so slightly wrong.

**Comment by shaggywolfhound** [comment]
Ok I'm a donkey.  I've been trying to load TM2 maps!!  All works now although got some configuration to do, but I can sort that.  Do you know if you can do the samething for TM2?

**Comment by Harha** [comment]
Sorry I've been busy with other stuff so I forgot to reply.

What do you mean by "Do you know if you can do the samething for TM2"?

**Comment by shaggywolfhound** [comment]
Meant as in dedicated server?
It seems I have everything running now accept the all important connection to it.  All the logs look fine and I've tried various different formats and I have 2350 and 3450 open, but still no luck.  I've used the uplay connect link plus generated my own maniaplanet link (although unsure what port is required for the link).  Also added a Packs volume in since I might need it. Will get there eventually.  Also no apologies, your giving me a hand to get working so no complaints here.

**Comment by Harha** [comment]
This docker image supports only these titles.

* Trackmania
* SMStorm
* TMCanyon
* TMStadium
* TMValley
* TMLagoon

I've never played Trackmania 2, but I think it's not supported by the dedicated server exe this docker image is setup to run.
edit: Or wait, I think Trackmania 2 is Stadium? In that case you just have to change the SERVER_TITLE environment variable in the docker-compose.yaml file.
